sudo: false
language: ruby

rvm:
- 3.1
- 3.0
- 2.7
- 2.6
- 2.5
- 2.4
- ruby-head
- jruby-9.2.11.1
- truffleruby-20.2.0

matrix:
  allow_failures:
    - rvm: 2.4
    - rvm: ruby-head
#   fast_finish: true
